### ISSUE TITLE
Sites with null identifier

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#2]
There are two sites in the PROPERTY_I column. I propose making up names for them so we know they're fake. I'm happy to do it as long as it doesn't have an impact on the forms.

**Comment by SVisovsky-NYCDPR** [comment]
Yeah, we can do that. Hudson River Park isn't even ours, it's state. But that's where UPS has that trailer on top of a parking garage or whatever it is. Pier 15 is supposedly ours, but I'm not sure I actually believe it.

**Comment by GeoDan87** [comment]
I added fake ids for these two sites because we need unique identifiers for them and well they are kind of fake.

UPS_HRP: Hudson River Park
UPS_P15: Pier 15
