### ISSUE TITLE
Consider removing edit access to Patrol App

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#4]
I've notice there are changes being made after data is submitted. Unless there is auditing enabled this seems like it should be turned off. I noticed that comments (at least) were being removed and edited in the consolidated sheets. I also accidentally made (and then reverted) an edit. This makes building a pipeline more difficult because there is no logic dictating when and how data can change.

**Comment by IPM-Annette** [comment]
Hey Dan - Sara mentioned this to me today. I agree - there are some fields that needs to be edited (wrong date/time, typo on numbers, etc.) and some fields that should not change at all (comments, properties, etc.).

Sara is going to call a meeting with Patricia, Julia, and our team to discuss this.

**Comment by GeoDan87** [comment]
@IPM-Annette sounds good! Thank you for considering the change and for the update!

**Comment by GeoDan87** [comment]
Thank you again @IPM-Annette for setting up the meeting with and locking down the timestamp and site columns!
