### ISSUE TITLE
Need to add borough to webmerc_centroids sheet

### ISSUE THREAD

**Issue by SVisovsky-NYCDPR** [NYC-Parks/consolidation_crowds_data#5]
Because we're not using a unique ID in the questions on the google form, but we do have borough in the combined sheet, I need to add borough (full name, not abbreviation) to the webmerc_centroids sheet. Any problems with that?

Not having this means things like St. Mary's Park (Brooklyn) gets confused with St. Mary's Park (Bronx) in Tableau because currently they're only joining on name.  I can add it myself, but I don't want to mess up what @GeoDan87 is doing without advanced notice.

**Comment by GeoDan87** [comment]
@SVisovsky-NYCDPR that should be fine! Thanks for the heads up!

**Comment by GeoDan87** [comment]
@GeoDan87 need to add this in the python scripts and in the SQL table.

**Comment by SVisovsky-NYCDPR** [comment]
Should I add it to the google sheet or will that break things?

**Comment by GeoDan87** [comment]
It should be okay

**Comment by SVisovsky-NYCDPR** [comment]
Done.
