### ISSUE TITLE
What is this site list?

### ISSUE THREAD

**Issue by GeoDan87** [NYC-Parks/consolidation_crowds_data#7]
Does [this site list](https://docs.google.com/spreadsheets/d/1DUr3w455j3pDpgwItFAdH6J4LSepdJBBZ-SkLQtyID0/edit#gid=1362448555) feed the interagency ambassador app? Does it relate to the other one?

**Comment by SVisovsky-NYCDPR** [comment]
I have no idea where this one came from. It probably only feeds the pivots in that google sheet. Probably.
